#!/usr/bin/env bash

alias l='ls'
alias ll='ls -la'
alias lll='ls -lart'

if [ -x "$(command -v bat)" ]; then
  alias cat='bat'
  alias less='bat'
else
  alias cat='batcat'
  alias less='batcat'
fi

alias gcat='/bin/cat'
alias gless='/usr/bin/less'

alias inetip='curl -4 -s "http://ipinfo.io"'

alias diff='colordiff'
alias uuidgen='uuidgen | tr "[:upper:]" "[:lower:]"'
