#!/usr/bin/env bash

alias l='ls'
alias ll='ls -la'
alias lll='ls -lart'

alias cat='batcat'
alias less='batcat'

alias gcat='/bin/cat'
alias gless='/usr/bin/less'

alias diff='colordiff'
alias uuidgen='uuidgen | tr "[:upper:]" "[:lower:]"'
